export const initialState: FormStateType = {
  // Father Details
  // FatherFirstName: "",
  // FatherMiddleName: "",
  // FatherLastName: "",
  // FatherPhoneNo: "",
  // FatherEmail: "",
  // FatherBloodGroup: "",
  // FatherAdharCardFront: null,
  // FatherAdharCardBack: null,
  // FatherVoterCardFront: null,
  // FatherVoterCardBack: null,
  // FatherOptionalCardFront: null,
  // FatherOptionalCardBack: null,

  // Mother Details
  // MotherFirstName: "",
  // MotherMiddleName: "",
  // MotherLastName: "",
  // MotherPhoneNo: "",
  // MotherEmail: "",
  // MotherBloodGroup: "",
  // MotherAdharCardFront: null,
  // MotherAdharCardBack: null,
  // MotherVoterCardFront: null,
  // MotherVoterCardBack: null,
  // MotherOptionalCardFront: null,
  // MotherOptionalCardBack: null,

  // Student Details
  // StudentFirstName: "",
  // StudentMiddleName: "",
  // StudentLastName: "",
  // StudentPhoneNo: "",
  // StudentEmail: "",
  // StudentBloodGroup: "",
  // StudentAdharCardFront: "",
  // StudentAdharCardBack: "",
  // StudentSchoolIdCardFront: "",

  // Address Details
  // Add: "",
  // State: "",
  // District: "",
  // City: "",
  // Area: "",
  // Pincode: "",

  // Payment Details
  // PaymentAmount: "",
  // PaymentStatus: "",

  // Teacher Details
  TeacherFirstName: "",
  TeacherMiddleName: "",
  TeacherLastName: "",
  TeacherPhoneNo: "",
  TeacherEmail: "",
  TeacherPassword: "",
  TeacherBranchId: "",
  TeacherDOB: "",
  TeacherBloodGroup: "",
  TeacherSex: "",
  TeacherProfileCardFront: null,
  TeacherAadharCardFront: null,
  TeacherAadharCardBack: null,
  TeacherVoterCardFront: null,
  TeacherVoterCardBack: null,
  TeacherPanCardFront: null,
  TeacherPassportCardFront: null,
  TeacherDrivingCardFront: null,
  TeacherDrivingCardBack: null,
  TeacherAddressStreet: "",
  TeacherAddressArea: "",
  TeacherAddressState: "",
  TeacherAddressDistrict: "",
  TeacherAddressCity: "",
  TeacherAddressPincode: 0,
  TeacherAddressCountry: "India",

  // Volunteer Details
  VolunteerFirstName: "",
  VolunteerMiddleName: "",
  VolunteerLastName: "",
  VolunteerPhoneNo: "",
  VolunteerEmail: "",
  VolunteerPassword: "",
  VolunteerBranchId: "",
  VolunteerDOB: "",
  VolunteerBloodGroup: "",
  VolunteerSex: "",
  VolunteerProfileCardFront: null,
  VolunteerAadharCardFront: null,
  VolunteerAadharCardBack: null,
  VolunteerVoterCardFront: null,
  VolunteerVoterCardBack: null,
  VolunteerPanCardFront: null,
  VolunteerPassportCardFront: null,
  VolunteerDrivingCardFront: null,
  VolunteerDrivingCardBack: null,
  VolunteerAddressStreet: "",
  VolunteerAddressArea: "",
  VolunteerAddressState: "",
  VolunteerAddressDistrict: "",
  VolunteerAddressCity: "",
  VolunteerAddressPincode: 0,
  VolunteerAddressCountry: "India",
};
