export const initialState: FormStateType = {
  // Father Details
  // FatherFirstName: "",
  // FatherMiddleName: "",
  // FatherLastName: "",
  // FatherPhoneNo: "",
  // FatherEmail: "",
  // FatherBloodGroup: "",
  // FatherAdharCardFront: null,
  // FatherAdharCardBack: null,
  // FatherVoterCardFront: null,
  // FatherVoterCardBack: null,
  // FatherOptionalCardFront: null,
  // FatherOptionalCardBack: null,

  // Mother Details
  // MotherFirstName: "",
  // MotherMiddleName: "",
  // MotherLastName: "",
  // MotherPhoneNo: "",
  // MotherEmail: "",
  // MotherBloodGroup: "",
  // MotherAdharCardFront: null,
  // MotherAdharCardBack: null,
  // MotherVoterCardFront: null,
  // MotherVoterCardBack: null,
  // MotherOptionalCardFront: null,
  // MotherOptionalCardBack: null,

  // Student Details
  // StudentFirstName: "",
  // StudentMiddleName: "",
  // StudentLastName: "",
  // StudentPhoneNo: "",
  // StudentEmail: "",
  // StudentBloodGroup: "",
  // StudentAdharCardFront: "",
  // StudentAdharCardBack: "",
  // StudentSchoolIdCardFront: "",

  // Address Details
  // Add: "",
  // State: "",
  // District: "",
  // City: "",
  // Area: "",
  // Pincode: "",

  // Payment Details
  // PaymentAmount: "",
  // PaymentStatus: "",

  // Teacher Details
  TeacherFirstName: "",
  TeacherMiddleName: "",
  TeacherLastName: "",
  TeacherPhoneNo: "",
  TeacherEmail: "",
  TeacherPassword: "",
  TeacherBranchId: "",
  TeacherDOB: "",
  TeacherBloodGroup: "",
  TeacherSex: "",
  TeacherProfileCardFront: null,
  TeacherAadharCardFront: null,
  TeacherAadharCardBack: null,
  TeacherVoterCardFront: null,
  TeacherVoterCardBack: null,
  TeacherPanCardFront: null,
  TeacherPassportCardFront: null,
  TeacherDrivingCardFront: null,
  TeacherDrivingCardBack: null,
  TeacherAddress: {
    Street: "hello",
    State: "",
    District: "",
    City: "",
    Area: "",
    Pincode: 0,
    Country: "",
  },

  // Volunteer Details
  // VolunteerFirstName: "",
  // VolunteerMiddleName: "",
  // VolunteerLastName: "",
  // VolunteerPhoneNo: "",
  // VolunteerEmail: "",
  // VolunteerBloodGroup: "",
  // VolunteerAdharCardFront: null,
  // VolunteerAdharCardBack: null,
  // VolunteerVoterCardFront: null,
  // VolunteerVoterCardBack: null,
  // VolunteerOptionalCardFront: null,
  // VolunteerOptionalCardBack: null,
};
